security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:          ^/
            form_login:
                #provider:     fos_userbundle
                #remember_me:  true
                csrf_provider: form.csrf_provider
            remember_me:
                key:          %secret%
            logout:           true
            anonymous:        true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:     ROLE_ADMIN
        ROLE_ADMIN_AFM: ROLE_USER
